# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appName', models.CharField(default=None, max_length=10, verbose_name='应用名称')),
                ('appEnglishName', models.CharField(default=None, max_length=20, unique=True, verbose_name='应用英文名称')),
                ('createDatetime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('isAlive', models.BooleanField(default=False, verbose_name='是否还在使用')),
                ('logo', models.CharField(default=None, max_length=30, verbose_name='LOGO地址')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(default=0, help_text='更新越重要，level越小', verbose_name='更新等级')),
                ('note', models.CharField(max_length=10, verbose_name='简短等级解释')),
                ('relatedApp', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Apps.Apps', verbose_name='关联应用')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default=None, max_length=30, verbose_name='版本号')),
                ('updateDatetime', models.DateTimeField(auto_now_add=True, verbose_name='更新日期')),
                ('url', models.CharField(default=None, max_length=200, verbose_name='应用下载地址')),
                ('isAlive', models.BooleanField(default=True, verbose_name='是否还在使用')),
                ('isLevelLatest', models.BooleanField(default=True, verbose_name='是否当前等级最新版')),
                ('descriptionEncoded', models.CharField(default=None, max_length=1000, verbose_name='更新说明')),
                ('md5', models.CharField(default=None, max_length=32, verbose_name='安装包MD5校验')),
                ('sha1', models.CharField(default=None, max_length=40, verbose_name='安装包SHA1校验')),
                ('relatedApp', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Apps.Apps', verbose_name='关联应用')),
                ('relatedLevel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Apps.Level', verbose_name='关联等级')),
            ],
        ),
    ]
