# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='logo',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='LOGO地址'),
        ),
        migrations.AlterField(
            model_name='level',
            name='note',
            field=models.CharField(default=None, max_length=10, verbose_name='简短等级解释'),
        ),
    ]
