# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0002_auto_20170220_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='description',
            field=models.CharField(default=None, max_length=1000, verbose_name='应用描述'),
        ),
    ]
