# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0004_auto_20170221_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='description',
            field=models.CharField(default=None, max_length=1000, null=True, verbose_name='应用描述'),
        ),
    ]
